version: 2
jobs:
    build:
        docker: #Docker executor type
            - image: circleci/node:4.8.2 #Container where you are going to execute the commands.
        steps:
            - checkout #Checkout the code in the project directory
            - run: echo "Hello world"
    deploy:
        docker: #Doker image to use aws resources
            - image: circleci/python:2.7-jessie
        working_directory: ~/circleci-docs
        buid_parameters:
            BUCKET_REPO: "mach-mobile-automation-repos"
            TEST_REPO: "test"
        steps:
            - run:
                name: Install awscli
                command: sudo pip install awscli
            - run:
                name: Get S3 info
                command: sudo aws s3 ls s3://$BUCKET_REPO/$TEST_REPO/

workflows:
    version: 2
    build-deploy:
        jobs:
            - build
            - deploy:
                requires:
                    - build
                filters:
                    branches:
                        only: master

              
