version: 2
jobs:
  checkout-test:
    docker: #Docker executor type
      - image: circleci/node:4.8.2 #Container where you are going to execute the commands.
    steps:
      - checkout #Checkout the code in the project directory
      - run:
          name: "Get directory name and get info"
          command: pwd && ls -all
      - persist_to_workspace:
          root: ./
          paths:
            - .circleci
  aws-test:
    docker: #Doker image to use aws resources
      - image: circleci/python:2.7-jessie
    environment:
      BUCKET_REPO: "mach-mobile-automation-repos"
      TEST_REPO: "test"
      PROJECT_NAME: "pipeline-ios-project"
      DEVICE_POOL_NAME: "IOS PIPELINE POOL"
      RUN_NAME: "Smoke-CircleCI-Test"
      IPA_PATH: "./machApp/build"
      IPA_FILE: "machApp"
      PLATFORM: "ios"
      PLATFORM_ENV: "staging"       #[dev, staging, automation]
      IPA_OUTPUT_LOG: "machApp.log"
      TEST_OUTPUT_LOG: "test-output.log"
      TEST_TYPE: "smoke"        #[smoke, regression] << For future changes
      AVAILABLE_TESTS: "available-ios-tests"
      TEST_ARN_LIST_FILE: "smoke-test-arn-list"
      CIRCLECI_DIR: ".circleci"
      ENV: "prod"               #Pipeline environments [-ops, -prod]
    steps:
      - attach_workspace:
          at: ./
      - run:
          name: Install awscli
          command: sudo pip install awscli
      - run:
          name: Get IPA file from S3
          command: |
            aws s3 cp s3://${BUCKET_REPO}/${PLATFORM}/${IPA_FILE} ./${IPA_FILE}
            pwd && ls -all
      - run:
          name: Send Smoke test to AWS Device Farm
          command: chmod 755 ./${CIRCLECI_DIR}/circleci-smoke-test.sh && ./${CIRCLECI_DIR}/circleci-smoke-test.sh

  aws-smoke-test:
    docker: #Doker image to use aws resources
      - image: circleci/python:2.7-jessie
    environment:
      BUCKET_REPO: "mach-mobile-automation-repos"
      TEST_REPO: "test"
      PROJECT_NAME: "pipeline-ios-project"
      DEVICE_POOL_NAME: "IOS PIPELINE POOL"
      RUN_NAME: "Smoke-CircleCI-Test"
      IPA_PATH: "./machApp/build"
      IPA_FILE: "machApp"
      PLATFORM: "ios"
      PLATFORM_ENV: "staging"       #[dev, staging, automation]
      IPA_OUTPUT_LOG: "machApp.log"
      TEST_OUTPUT_LOG: "test-output.log"
      TEST_TYPE: "smoke"        #[smoke, regression] << For future changes
      AVAILABLE_TESTS: "available-ios-tests"
      TEST_ARN_LIST_FILE: "smoke-test-arn-list"
      CIRCLECI_DIR: ".circleci"
      ENV: "-prod"               #Pipeline environments [-ops, -prod]
    steps:
      - attach_workspace:
          at: ./
      - run:
          name: Install awscli
          command: sudo pip install awscli
      - run:
          name: Send Smoke test to AWS Device Farm
          command: chmod 755 ./${CIRCLECI_DIR}/circleci-smoke-test.sh && ./${CIRCLECI_DIR}/circleci-smoke-test.sh
workflows:
  version: 2
  test-in-devicefarm:
    jobs:
      - checkout-test:
          filters:
            branches:
              only: master
      - aws-test:
          requires:
            - checkout-test
  test-in-device-farm2:
    jobs:
      - checkout-test:
          filters:
            branches:
              only: aws-communication
      - aws-smoke-test:
          requires:
            - checkout-test
