# Uncomment the next line to define a global platform for your project
platform :ios, '9.3'
inhibit_all_warnings!

source 'https://github.com/bcilabs/mach-ios-podspec.git'
source 'https://github.com/CocoaPods/Specs.git'

target 'machApp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for machApp
  pod 'Alamofire' #, '~> 4.5'
  pod 'SwiftyJSON' #, '~> 3.1.4'
  pod 'Swinject' #, '~> 2.1.0'
  pod 'SwinjectStoryboard' #, '1.1.1'
  pod 'KeychainSwift' #, '~> 8.0.2'
  pod 'EZSwiftExtensions', '~> 1.11'
  pod 'Unbox' #, '~> 2.5.0'
  pod 'UnboxedAlamofire' #, '~> 2.0.3'
  pod 'Wrap' #, '~> 2.1.1'
  pod 'HockeySDK', :subspecs => ['AllFeaturesLib'] #, :configuration => 'staging'
  pod 'RealmSwift' #, '~> 2.5.1'
  pod 'PubNub' #, '~> 4.6.3'
  pod 'SDWebImage'#, '4.4.1'
  pod 'DropDown' #, '~> 2.0'
  pod 'lottie-ios', '~> 2.1.5'
  pod 'ActiveLabel'#, '~> 0.7.1'
  pod 'Branch'
  pod 'EFCountingLabel'# , '4.0.1'
  pod 'Analytics'#, '~> 3.0'
  pod 'NewRelicAgent'
  pod 'MachZendesk'
  pod 'SwiftLint'   
  pod 'Sift'
  pod 'Firebase/Core'
  pod 'Firebase/Performance'
  pod 'Fabric', '~> 1.7.11'
  pod 'Crashlytics', '~> 3.10.7'

  target 'machAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'machAppUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.name == 'EZSwiftExtensions'
      target.build_configurations.each do |config|
        config.build_settings['SWIFT_VERSION'] = '3.0'
      end
    else 
      target.build_configurations.each do |config|
        config.build_settings['SWIFT_VERSION'] = '4.0'
      end
    end
  end
end
